### ISSUE TITLE
请问下如何使用

### ISSUE THREAD

**Issue by r1172464137** [dateolive/suiji-gaokao-html#1]
有点懵逼

**Comment by dateolive** [comment]
将整个demo直接上传到服务器，通过域名的形式指定目录访问即可，如果有什么疑问，可以加我qq2448282543

**Comment by dateolive** [comment]
> 有点懵逼

将整个demo直接上传到服务器，通过域名的形式指定目录访问即可，如果有什么疑问，可以加我qq2448282543
